---
- name: Install Docker (for SonarQube container)
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Run SonarQube container
  docker_container:
    name: sonarqube
    image: sonarqube:lts
    state: started
    restart_policy: always
    ports:
      - "9000:9000"
